### ISSUE TITLE
Label and reference highlighting breaks at underscores

### ISSUE THREAD

**Issue by cdesaintguilhem** [Ziqi-Yang/typst-mode.el#7]
Hi there, I've noticed that the syntax colouring in Emacs breaks when labels and references contain underscores. Here is a minimal example:

```
#set heading(numbering: "1")

= Introduction <intro_duction>

This is @intro_duction.
```
which colours as such:
<img width="259" alt="image" src="https://github.com/Ziqi-Yang/typst-mode.el/assets/2855995/6fb5d3b7-6e79-44a5-93fe-de9fe2132140">

Thanks for the work on the emacs mode!

**Comment by Ziqi-Yang** [comment]
Sorry for the late reply. I'm traveling at that time.   
The issue is solved now.
 Thank you for reporting this issue! <3
